config { type: "table" }

WITH Sequences AS
  (
    SELECT 
    id,
    split(tags, "|") as splitted_tag,
    PARSE_DATE('%Y-%m-%d', FORMAT_DATE('%Y-%m-01', date(creation_date))) as date
    FROM `bigquery-public-data.stackoverflow.posts_questions` 
  )
SELECT tag, date, count(*) as count
FROM Sequences
CROSS JOIN UNNEST(Sequences.splitted_tag) AS tag
GROUP BY tag, date
ORDER BY date ASC, count DESC